import "./globals.css";
import Nav from "./components/Nav";
import { getServerSession } from "next-auth";

// import { authOptions } from '@/pages/api/auth/[...nextauth]'

export const metadata = {
	title: "Agile & Pixels",
	description: "Generated by DnZ apps",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	// const session = await getServerSession(authOptions)

	return (
		<html lang="en">
			<body className="bg-mainBgColor max-w-custom mx-auto flex flex-col items-center min-h-screen">
				<Nav />
				{children}
			</body>
		</html>
	);
}
